name: "mkdocs-build-action"
description: "Github action to build an MkDocs site and upload to S3"
author: vini
inputs:
  python-version:
    description: The Python version to use.
    default: '3.9'
    required: true
outputs:
  built_dir:
    description: 'Directory containing the built documentation website'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: composite-script.sh ${{ inputs.python-version }}
      shell: bash
    - run: docker ps
      shell: bash

