name: "mkdocs-build-action"
description: "Github action to build an MkDocs site and upload to S3"
author: vini
runs:
  using: "docker"
  image: ${{ env.DOCKER_IMAGE }}
  entrypoint: 'entrypoint.sh'
outputs:
  built_dir:
    description: 'Directory containing the built documentation website'
inputs:
  python-version:
    description: The Python version to use.
    default: '3.9'
    required: true
env:
  DOCKER_IMAGE: "python:${{ inputs.python-version }}-buster"
